### ISSUE TITLE
Issues building within a monorepo

### ISSUE THREAD

**Issue by chrisdrackett** [diez/diez#51]
I'm trying to use Diez in a yarn workspaces monorepo and have been running into issues. If I use the stock `tsconfig.json` the build fails with errors from my other packages:

```
error TS6059: File '/Users/cwd/src/project/server/src/auth.ts' is not under 'rootDir' '/Users/cwd/src/project/design/src'. 'rootDir' is expected to contain all source files.
```

I've tried adding a `rootDir` to the config, but then I get:

```
Unable to proceed: TypeScript configuration at does not compile from src/. Please fix the TypeScript configuration and try again.
```

Another thing I've tried is extending my base typescript config from the root of my project. When I do this I get the following:

```
Cannot read property 'options' of undefined
```

This is what the other projects in our monorepo do without issue, so I feel like this one is the closest, but still runs into issues.

if I remove the `design` folder from the monorepo and run build it completes without issue. This is currently what we have to do whenever we make changes, but this effectively means nobody wants to ever change the design system, the exact opposite of what we're trying to use Diez for!

I know usage within a monorepo might not yet be supported, but I'd love to get this working if at all possible!

**Comment by zackbrown** [comment]
Hey Chris,

For a working example of a Diez project + yarn workspaces: refer to the Diez monorepo itself.  The `examples` directory includes Diez design language projects like the [Lorem Ipsum](https://github.com/diez/diez/tree/master/examples/lorem-ipsum/design-language) starter project.

Since `tsconfig`s & `package.json`s can vary wildly, the best I can offer is some diagnosis and suggested approaches.

**Approach:**  check out Diez's root [package.json](https://github.com/diez/diez/blob/master/package.json) and [tsconfig.json](https://github.com/diez/diez/blob/master/tsconfig.json) as well as sub-projects' config like [Lorem Ipsum's package.json](https://github.com/diez/diez/blob/master/examples/lorem-ipsum/design-language/package.json) and [Lorem Ipsum's tsconfig.json](https://github.com/diez/diez/blob/master/examples/lorem-ipsum/design-language/tsconfig.json).  See if there are significant deltas between this and your own setup.

**Approach:**  Google search for these error messages + "yarn workspaces" and "typescript"

**Diagnosis:** **The `rootDir` error is very likely due to a `node_modules` folder trying to get compiled by `tsc`.** (An issue due to the symlinking of other workspaces' .ts source files into node_modules via yarn workspaces.)  You don't want this.  

If the above is indeed the issue, to resolve:
1. ensure that your Diez project's tsconfig.json:
  a.) explicitly points to a `rootDir` that doesn't contain node_modules (i.e. not `.`, and e.g. something like `src`) and
  b.) `include`'s only .ts files underneath that `src` directory. 
For reference, see [Lorem Ipsum's tsconfig.json](https://github.com/diez/diez/blob/master/examples/lorem-ipsum/design-language/tsconfig.json)

2. if needed, add an explicit `exclude` directive for `node_modules` to your Diez project's (and/or root project's) tsconfig.json:

```
"exclude": [
        "node_modules"
]
```

[Read more about `exclude`](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#examples) in the TS docs.
